### ISSUE TITLE
Problem with git/repo

### ISSUE THREAD

**Issue by jaclas** [gabr42/DelphiLens#1]
I use Source Tree, when I try pull last 2 commits I get error:

git -c diff.mnemonicprefix=false -c core.quotepath=false fetch origin

git -c diff.mnemonicprefix=false -c core.quotepath=false pull origin master
From https://github.com/gabr42/DelphiLens
 * branch            master     -> FETCH_HEAD

Already up-to-date.

git -c diff.mnemonicprefix=false -c core.quotepath=false submodule update --init --recursive
fatal: Needed a single revision
Unable to find current revision in submodule path 'DelphiAST/Source/FreePascalSupport/FPC_StringBuilder'
Failed to recurse into submodule path 'DelphiAST'
Completed with errors, see above.

My git knowledge is poor, please help :-)

**Comment by gabr42** [comment]
My git knowledge is also poor, sorry. 

This question: https://stackoverflow.com/q/3796927/4997 indicates that using `--recurse-submodules` is the right thing.

Personally, I use GitKraken which initializes submodules for me.
