### ISSUE TITLE
Problem with install latest version of DelphiLens

### ISSUE THREAD

**Issue by jaclas** [gabr42/DelphiLens#13]
After compile all packages I try install main project and I get external exception:

![vps_2018 05 08_02](https://user-images.githubusercontent.com/17312717/39783851-b3577ef0-5316-11e8-824f-09fc4047d71c.png)

Delphi Tokyo 10.2

**Comment by gabr42** [comment]
DelphiLens is still very pre-alpha and in '*sometimes* works on my machine'. Current HEAD is not working very well and I'm fixing that right now.

At the moment you can check out https://github.com/gabr42/DelphiLens/releases/tag/mostly-stable-version-1 which is the last known stable version.
